'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=4.0.30319.1.
'
Namespace PWX

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.peaksware.com/PWX/1/0"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.peaksware.com/PWX/1/0", IsNullable:=False)> _
    Partial Public Class pwx

        Private workoutField() As pwxWorkout

        Private extensionField As pwxExtension

        Private versionField As String

        Private creatorField As String

        Public Sub New()
            MyBase.New()
            Me.versionField = "1.0"
        End Sub

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("workout")> _
        Public Property workout() As pwxWorkout()
            Get
                Return Me.workoutField
            End Get
            Set(value As pwxWorkout())
                Me.workoutField = value
            End Set
        End Property

        '''<remarks/>
        Public Property extension() As pwxExtension
            Get
                Return Me.extensionField
            End Get
            Set(value As pwxExtension)
                Me.extensionField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property version() As String
            Get
                Return Me.versionField
            End Get
            Set(value As String)
                Me.versionField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property creator() As String
            Get
                Return Me.creatorField
            End Get
            Set(value As String)
                Me.creatorField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.peaksware.com/PWX/1/0")> _
    Partial Public Class pwxWorkout

        Private athleteField As athlete

        Private goalField As String

        Private sportTypeField As sportTypes

        Private sportTypeFieldSpecified As Boolean

        Private titleField As String

        Private cmtField As String

        Private codeField As String

        Private deviceField As device

        Private timeField As Date

        Private timeFieldSpecified As Boolean

        Private summarydataField As summaryData

        Private segmentField() As pwxWorkoutSegment

        Private sampleField() As pwxWorkoutSample

        Private extensionField As pwxWorkoutExtension

        Private idField As String

        '''<remarks/>
        Public Property athlete() As athlete
            Get
                Return Me.athleteField
            End Get
            Set(value As athlete)
                Me.athleteField = value
            End Set
        End Property

        '''<remarks/>
        Public Property goal() As String
            Get
                Return Me.goalField
            End Get
            Set(value As String)
                Me.goalField = value
            End Set
        End Property

        '''<remarks/>
        Public Property sportType() As sportTypes
            Get
                Return Me.sportTypeField
            End Get
            Set(value As sportTypes)
                Me.sportTypeField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property sportTypeSpecified() As Boolean
            Get
                Return Me.sportTypeFieldSpecified
            End Get
            Set(value As Boolean)
                Me.sportTypeFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property title() As String
            Get
                Return Me.titleField
            End Get
            Set(value As String)
                Me.titleField = value
            End Set
        End Property

        '''<remarks/>
        Public Property cmt() As String
            Get
                Return Me.cmtField
            End Get
            Set(value As String)
                Me.cmtField = value
            End Set
        End Property

        '''<remarks/>
        Public Property code() As String
            Get
                Return Me.codeField
            End Get
            Set(value As String)
                Me.codeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property device() As device
            Get
                Return Me.deviceField
            End Get
            Set(value As device)
                Me.deviceField = value
            End Set
        End Property

        '''<remarks/>
        Public Property time() As Date
            Get
                Return Me.timeField
            End Get
            Set(value As Date)
                Me.timeField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property timeSpecified() As Boolean
            Get
                Return Me.timeFieldSpecified
            End Get
            Set(value As Boolean)
                Me.timeFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property summarydata() As summaryData
            Get
                Return Me.summarydataField
            End Get
            Set(value As summaryData)
                Me.summarydataField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("segment")> _
        Public Property segment() As pwxWorkoutSegment()
            Get
                Return Me.segmentField
            End Get
            Set(value As pwxWorkoutSegment())
                Me.segmentField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("sample")> _
        Public Property sample() As pwxWorkoutSample()
            Get
                Return Me.sampleField
            End Get
            Set(value As pwxWorkoutSample())
                Me.sampleField = value
            End Set
        End Property

        '''<remarks/>
        Public Property extension() As pwxWorkoutExtension
            Get
                Return Me.extensionField
            End Get
            Set(value As pwxWorkoutExtension)
                Me.extensionField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property id() As String
            Get
                Return Me.idField
            End Get
            Set(value As String)
                Me.idField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.peaksware.com/PWX/1/0")> _
    Partial Public Class athlete

        Private nameField As String

        Private weightField As Double

        Private weightFieldSpecified As Boolean

        '''<remarks/>
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set(value As String)
                Me.nameField = value
            End Set
        End Property

        '''<remarks/>
        Public Property weight() As Double
            Get
                Return Me.weightField
            End Get
            Set(value As Double)
                Me.weightField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property weightSpecified() As Boolean
            Get
                Return Me.weightFieldSpecified
            End Get
            Set(value As Boolean)
                Me.weightFieldSpecified = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.peaksware.com/PWX/1/0")> _
    Partial Public Class minMaxAvg

        Private maxField As Double

        Private maxFieldSpecified As Boolean

        Private minField As Double

        Private minFieldSpecified As Boolean

        Private avgField As Double

        Private avgFieldSpecified As Boolean

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property max() As Double
            Get
                Return Me.maxField
            End Get
            Set(value As Double)
                Me.maxField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property maxSpecified() As Boolean
            Get
                Return Me.maxFieldSpecified
            End Get
            Set(value As Boolean)
                Me.maxFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property min() As Double
            Get
                Return Me.minField
            End Get
            Set(value As Double)
                Me.minField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property minSpecified() As Boolean
            Get
                Return Me.minFieldSpecified
            End Get
            Set(value As Boolean)
                Me.minFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property avg() As Double
            Get
                Return Me.avgField
            End Get
            Set(value As Double)
                Me.avgField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property avgSpecified() As Boolean
            Get
                Return Me.avgFieldSpecified
            End Get
            Set(value As Boolean)
                Me.avgFieldSpecified = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.peaksware.com/PWX/1/0")> _
    Partial Public Class summaryData

        Private beginningField As Double

        Private durationField As Double

        Private durationstoppedField As Double

        Private durationstoppedFieldSpecified As Boolean

        Private workField As Double

        Private workFieldSpecified As Boolean

        Private tssField As Double

        Private tssFieldSpecified As Boolean

        Private normalizedPowerField As Double

        Private normalizedPowerFieldSpecified As Boolean

        Private hrField As minMaxAvg

        Private spdField As minMaxAvg

        Private pwrField As minMaxAvg

        Private torqField As minMaxAvg

        Private cadField As minMaxAvg

        Private distField As Double

        Private distFieldSpecified As Boolean

        Private altField As minMaxAvg

        Private tempField As minMaxAvg

        Private variabilityIndexField As Integer

        Private variabilityIndexFieldSpecified As Boolean

        Private climbingelevationField As Double

        Private climbingelevationFieldSpecified As Boolean

        Private descendingelevationField As Double

        Private descendingelevationFieldSpecified As Boolean

        Private extensionField As summaryDataExtension

        '''<remarks/>
        Public Property beginning() As Double
            Get
                Return Me.beginningField
            End Get
            Set(value As Double)
                Me.beginningField = value
            End Set
        End Property

        '''<remarks/>
        Public Property duration() As Double
            Get
                Return Me.durationField
            End Get
            Set(value As Double)
                Me.durationField = value
            End Set
        End Property

        '''<remarks/>
        Public Property durationstopped() As Double
            Get
                Return Me.durationstoppedField
            End Get
            Set(value As Double)
                Me.durationstoppedField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property durationstoppedSpecified() As Boolean
            Get
                Return Me.durationstoppedFieldSpecified
            End Get
            Set(value As Boolean)
                Me.durationstoppedFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property work() As Double
            Get
                Return Me.workField
            End Get
            Set(value As Double)
                Me.workField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property workSpecified() As Boolean
            Get
                Return Me.workFieldSpecified
            End Get
            Set(value As Boolean)
                Me.workFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property tss() As Double
            Get
                Return Me.tssField
            End Get
            Set(value As Double)
                Me.tssField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property tssSpecified() As Boolean
            Get
                Return Me.tssFieldSpecified
            End Get
            Set(value As Boolean)
                Me.tssFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property normalizedPower() As Double
            Get
                Return Me.normalizedPowerField
            End Get
            Set(value As Double)
                Me.normalizedPowerField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property normalizedPowerSpecified() As Boolean
            Get
                Return Me.normalizedPowerFieldSpecified
            End Get
            Set(value As Boolean)
                Me.normalizedPowerFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property hr() As minMaxAvg
            Get
                Return Me.hrField
            End Get
            Set(value As minMaxAvg)
                Me.hrField = value
            End Set
        End Property

        '''<remarks/>
        Public Property spd() As minMaxAvg
            Get
                Return Me.spdField
            End Get
            Set(value As minMaxAvg)
                Me.spdField = value
            End Set
        End Property

        '''<remarks/>
        Public Property pwr() As minMaxAvg
            Get
                Return Me.pwrField
            End Get
            Set(value As minMaxAvg)
                Me.pwrField = value
            End Set
        End Property

        '''<remarks/>
        Public Property torq() As minMaxAvg
            Get
                Return Me.torqField
            End Get
            Set(value As minMaxAvg)
                Me.torqField = value
            End Set
        End Property

        '''<remarks/>
        Public Property cad() As minMaxAvg
            Get
                Return Me.cadField
            End Get
            Set(value As minMaxAvg)
                Me.cadField = value
            End Set
        End Property

        '''<remarks/>
        Public Property dist() As Double
            Get
                Return Me.distField
            End Get
            Set(value As Double)
                Me.distField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property distSpecified() As Boolean
            Get
                Return Me.distFieldSpecified
            End Get
            Set(value As Boolean)
                Me.distFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property alt() As minMaxAvg
            Get
                Return Me.altField
            End Get
            Set(value As minMaxAvg)
                Me.altField = value
            End Set
        End Property

        '''<remarks/>
        Public Property temp() As minMaxAvg
            Get
                Return Me.tempField
            End Get
            Set(value As minMaxAvg)
                Me.tempField = value
            End Set
        End Property

        '''<remarks/>
        Public Property variabilityIndex() As Integer
            Get
                Return Me.variabilityIndexField
            End Get
            Set(value As Integer)
                Me.variabilityIndexField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property variabilityIndexSpecified() As Boolean
            Get
                Return Me.variabilityIndexFieldSpecified
            End Get
            Set(value As Boolean)
                Me.variabilityIndexFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property climbingelevation() As Double
            Get
                Return Me.climbingelevationField
            End Get
            Set(value As Double)
                Me.climbingelevationField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property climbingelevationSpecified() As Boolean
            Get
                Return Me.climbingelevationFieldSpecified
            End Get
            Set(value As Boolean)
                Me.climbingelevationFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property descendingelevation() As Double
            Get
                Return Me.descendingelevationField
            End Get
            Set(value As Double)
                Me.descendingelevationField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property descendingelevationSpecified() As Boolean
            Get
                Return Me.descendingelevationFieldSpecified
            End Get
            Set(value As Boolean)
                Me.descendingelevationFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property extension() As summaryDataExtension
            Get
                Return Me.extensionField
            End Get
            Set(value As summaryDataExtension)
                Me.extensionField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.peaksware.com/PWX/1/0")> _
    Partial Public Class summaryDataExtension

        Private anyField() As System.Xml.XmlElement

        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()> _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set(value As System.Xml.XmlElement())
                Me.anyField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.peaksware.com/PWX/1/0")> _
    Partial Public Class device

        Private makeField As String

        Private modelField As String

        Private stopdetectionsettingField As Double

        Private stopdetectionsettingFieldSpecified As Boolean

        Private elevationchangesettingField As Double

        Private elevationchangesettingFieldSpecified As Boolean

        Private extensionField As deviceExtension

        Private idField As String

        '''<remarks/>
        Public Property make() As String
            Get
                Return Me.makeField
            End Get
            Set(value As String)
                Me.makeField = value
            End Set
        End Property

        '''<remarks/>
        Public Property model() As String
            Get
                Return Me.modelField
            End Get
            Set(value As String)
                Me.modelField = value
            End Set
        End Property

        '''<remarks/>
        Public Property stopdetectionsetting() As Double
            Get
                Return Me.stopdetectionsettingField
            End Get
            Set(value As Double)
                Me.stopdetectionsettingField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property stopdetectionsettingSpecified() As Boolean
            Get
                Return Me.stopdetectionsettingFieldSpecified
            End Get
            Set(value As Boolean)
                Me.stopdetectionsettingFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property elevationchangesetting() As Double
            Get
                Return Me.elevationchangesettingField
            End Get
            Set(value As Double)
                Me.elevationchangesettingField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property elevationchangesettingSpecified() As Boolean
            Get
                Return Me.elevationchangesettingFieldSpecified
            End Get
            Set(value As Boolean)
                Me.elevationchangesettingFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property extension() As deviceExtension
            Get
                Return Me.extensionField
            End Get
            Set(value As deviceExtension)
                Me.extensionField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property id() As String
            Get
                Return Me.idField
            End Get
            Set(value As String)
                Me.idField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.peaksware.com/PWX/1/0")> _
    Partial Public Class deviceExtension

        Private anyField() As System.Xml.XmlElement

        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()> _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set(value As System.Xml.XmlElement())
                Me.anyField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.peaksware.com/PWX/1/0")> _
    Public Enum sportTypes

        '''<remarks/>
        Bike

        '''<remarks/>
        Run

        '''<remarks/>
        Walk

        '''<remarks/>
        Swim

        '''<remarks/>
        Brick

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Cross train")> _
        Crosstrain

        '''<remarks/>
        Race

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Day Off")> _
        DayOff

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("Mountain Bike")> _
        MountainBike

        '''<remarks/>
        Strength

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("XC Ski")> _
        XCSki

        '''<remarks/>
        Rowing

        '''<remarks/>
        Other
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.peaksware.com/PWX/1/0")> _
    Partial Public Class pwxWorkoutSegment

        Private nameField As String

        Private summarydataField As summaryData

        Private extensionField As pwxWorkoutSegmentExtension

        '''<remarks/>
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set(value As String)
                Me.nameField = value
            End Set
        End Property

        '''<remarks/>
        Public Property summarydata() As summaryData
            Get
                Return Me.summarydataField
            End Get
            Set(value As summaryData)
                Me.summarydataField = value
            End Set
        End Property

        '''<remarks/>
        Public Property extension() As pwxWorkoutSegmentExtension
            Get
                Return Me.extensionField
            End Get
            Set(value As pwxWorkoutSegmentExtension)
                Me.extensionField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.peaksware.com/PWX/1/0")> _
    Partial Public Class pwxWorkoutSegmentExtension

        Private anyField() As System.Xml.XmlElement

        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()> _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set(value As System.Xml.XmlElement())
                Me.anyField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.peaksware.com/PWX/1/0")> _
    Partial Public Class pwxWorkoutSample

        Private timeoffsetField As Double

        Private hrField As Byte

        Private hrFieldSpecified As Boolean

        Private spdField As Double

        Private spdFieldSpecified As Boolean

        Private pwrField As Short

        Private pwrFieldSpecified As Boolean

        Private torqField As Double

        Private torqFieldSpecified As Boolean

        Private cadField As Byte

        Private cadFieldSpecified As Boolean

        Private distField As Double

        Private distFieldSpecified As Boolean

        Private latField As Double

        Private latFieldSpecified As Boolean

        Private lonField As Double

        Private lonFieldSpecified As Boolean

        Private altField As Double

        Private altFieldSpecified As Boolean

        Private tempField As Double

        Private tempFieldSpecified As Boolean

        Private timeField As Date

        Private timeFieldSpecified As Boolean

        Private extensionField As pwxWorkoutSampleExtension

        '''<remarks/>
        Public Property timeoffset() As Double
            Get
                Return Me.timeoffsetField
            End Get
            Set(value As Double)
                Me.timeoffsetField = value
            End Set
        End Property

        '''<remarks/>
        Public Property hr() As Byte
            Get
                Return Me.hrField
            End Get
            Set(value As Byte)
                Me.hrField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property hrSpecified() As Boolean
            Get
                Return Me.hrFieldSpecified
            End Get
            Set(value As Boolean)
                Me.hrFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property spd() As Double
            Get
                Return Me.spdField
            End Get
            Set(value As Double)
                Me.spdField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property spdSpecified() As Boolean
            Get
                Return Me.spdFieldSpecified
            End Get
            Set(value As Boolean)
                Me.spdFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property pwr() As Short
            Get
                Return Me.pwrField
            End Get
            Set(value As Short)
                Me.pwrField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property pwrSpecified() As Boolean
            Get
                Return Me.pwrFieldSpecified
            End Get
            Set(value As Boolean)
                Me.pwrFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property torq() As Double
            Get
                Return Me.torqField
            End Get
            Set(value As Double)
                Me.torqField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property torqSpecified() As Boolean
            Get
                Return Me.torqFieldSpecified
            End Get
            Set(value As Boolean)
                Me.torqFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property cad() As Byte
            Get
                Return Me.cadField
            End Get
            Set(value As Byte)
                Me.cadField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property cadSpecified() As Boolean
            Get
                Return Me.cadFieldSpecified
            End Get
            Set(value As Boolean)
                Me.cadFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property dist() As Double
            Get
                Return Me.distField
            End Get
            Set(value As Double)
                Me.distField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property distSpecified() As Boolean
            Get
                Return Me.distFieldSpecified
            End Get
            Set(value As Boolean)
                Me.distFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property lat() As Double
            Get
                Return Me.latField
            End Get
            Set(value As Double)
                Me.latField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property latSpecified() As Boolean
            Get
                Return Me.latFieldSpecified
            End Get
            Set(value As Boolean)
                Me.latFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property lon() As Double
            Get
                Return Me.lonField
            End Get
            Set(value As Double)
                Me.lonField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property lonSpecified() As Boolean
            Get
                Return Me.lonFieldSpecified
            End Get
            Set(value As Boolean)
                Me.lonFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property alt() As Double
            Get
                Return Me.altField
            End Get
            Set(value As Double)
                Me.altField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property altSpecified() As Boolean
            Get
                Return Me.altFieldSpecified
            End Get
            Set(value As Boolean)
                Me.altFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property temp() As Double
            Get
                Return Me.tempField
            End Get
            Set(value As Double)
                Me.tempField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property tempSpecified() As Boolean
            Get
                Return Me.tempFieldSpecified
            End Get
            Set(value As Boolean)
                Me.tempFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property time() As Date
            Get
                Return Me.timeField
            End Get
            Set(value As Date)
                Me.timeField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property timeSpecified() As Boolean
            Get
                Return Me.timeFieldSpecified
            End Get
            Set(value As Boolean)
                Me.timeFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property extension() As pwxWorkoutSampleExtension
            Get
                Return Me.extensionField
            End Get
            Set(value As pwxWorkoutSampleExtension)
                Me.extensionField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.peaksware.com/PWX/1/0")> _
    Partial Public Class pwxWorkoutSampleExtension

        Private anyField() As System.Xml.XmlElement

        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()> _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set(value As System.Xml.XmlElement())
                Me.anyField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.peaksware.com/PWX/1/0")> _
    Partial Public Class pwxWorkoutExtension

        Private anyField() As System.Xml.XmlElement

        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()> _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set(value As System.Xml.XmlElement())
                Me.anyField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.peaksware.com/PWX/1/0")> _
    Partial Public Class pwxExtension

        Private anyField() As System.Xml.XmlElement

        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()> _
        Public Property Any() As System.Xml.XmlElement()
            Get
                Return Me.anyField
            End Get
            Set(value As System.Xml.XmlElement())
                Me.anyField = value
            End Set
        End Property
    End Class
End Namespace
